version: '3.8'
services:
  -=name=-:
    platform: linux/amd64
    -=image_block=-
    container_name: "zetachain_${NETWORK:-mainnet}_rpc"
    environment:
      DAEMON_HOME: "${DAEMON_HOME:-/root/.zetacored}"
      NETWORK: ${NETWORK:-mainnet}
      RESTORE_TYPE: "${RESTORE_TYPE:-snapshot}"
      SNAPSHOT_API: ${SNAPSHOT_API:-https://snapshots.rpc.zetachain.com}
      TRUST_HEIGHT_DIFFERENCE_STATE_SYNC: ${TRUST_HEIGHT_DIFFERENCE_STATE_SYNC:-40000}
      CHAIN_ID: "${CHAIN_ID:-zetachain_7000-1}"
      VISOR_NAME: "${VISOR_NAME:-cosmovisor}"
      DAEMON_NAME: "${DAEMON_NAME:-zetacored}"
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "${DAEMON_ALLOW_DOWNLOAD_BINARIES:-false}"
      DAEMON_RESTART_AFTER_UPGRADE: "${DAEMON_RESTART_AFTER_UPGRADE:-true}"
      UNSAFE_SKIP_BACKUP: "${UNSAFE_SKIP_BACKUP:-true}"
      MONIKER: ${MONIKER:-mainnet-docker-rpc}
      #If this is true it will erase everything and start over from scratch.
      RE_DO_START_SEQUENCE: "${RE_DO_START_SEQUENCE:-false}"
      #If this is true it will build the dockerfile and use binary from built docker file instead of remote docker image for local development testing on non-governance upgrades.
      IS_LOCAL_DEVELOPMENT: "${IS_LOCAL_DEVELOPMENT:-false}"
    ports:
      - "26656:26656"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
      - "26657:26657"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - -=name=-:/root/.zetacored/
    entrypoint: bash /scripts/start.sh
volumes:
  -=name=-:
